version: "3.9"

services:
  # MongoDB
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: techchallenge
    ports:
      - "27018:27017"
    networks:
      - fiap-network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  payment-simulator:
    image: docker.io/erickemprobr/procpag:latest
    platform: linux/amd64
    ports:
      - "8089:8089"
    networks:
      - fiap-network


  # Spring Boot App
  app:
    build: .
    container_name: fiap-tech-challenge-fase3
    ports:
      - "8081:8080"
    networks:
      - fiap-network
    depends_on:
      mongodb:
        condition: service_healthy
      # se o simulador tiver healthcheck, dá pra usar condition também
      payment-simulator:
        condition: service_started
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/techchallenge?retryWrites=true&serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
      JWT_SECRET_BASE64: wE5aP9xM8vKZbS4j8Q7mN2tYkP3rA1xCqWvL9uT0gHk=
      EXTERNAL_PAYMENT_BASE_URL: http://payment-simulator:8089

networks:
  fiap-network:
    driver: bridge

volumes:
  mongodb_data: