package br.com.fiap.techchallenge.core.domain.model;

import br.com.fiap.techchallenge.core.domain.enums.UserType;
import br.com.fiap.techchallenge.core.domain.exception.user.InvalidUserException;

import java.util.Objects;

public abstract class User {

    private final String id;
    private String name;
    private UserType userType;
    private String email;
    private String login;
    private String password;

    // Note: 'id' is intentionally not included in this constructor.
    // It will be generated by the persistence layer (MongoDB)
    // and can be added later if needed.
    protected User(String name, UserType type, String email, String login, String password) {
        this(null, name, type, email, login, password);
    }

    protected User(String id, String name, UserType type, String email, String login, String password) {
        this.id = id; // pode ser null na criação
        this.name = requireNonBlank(name, "name");
        this.userType = Objects.requireNonNull(type, "userType must not be null");
        this.email = requireValidEmail(email);
        this.login = requireNonBlank(login, "login");
        this.password = requireNonBlank(password, "password");
    }

    private String requireNonBlank(String value, String fieldName) {
        if (value == null || value.trim().isEmpty()) {
            throw new InvalidUserException(fieldName + " must not be null or blank");
        }
        return value;
    }

    private String requireValidEmail(String email) {
        if (email == null || email.trim().isEmpty()) {
            throw new InvalidUserException("email must not be null or blank");
        }
        // validação simples, suficiente pro domínio por enquanto
        if (!email.contains("@")) {
            throw new InvalidUserException("email must be a valid format");
        }
        return email;
    }


    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public UserType getUserType() {
        return userType;
    }

    public boolean isOwner() { return UserType.OWNER.equals(this.userType); }

    public String getEmail() {
        return email;
    }

    public String getLogin() {
        return login;
    }

    public String getPassword() {
        return password;
    }



    public void updateName(String name) {
        this.name = requireNonBlank(name, "name");
    }

    public void updateEmail(String email) {
        this.email = requireValidEmail(email);
    }

    public void updateLogin(String login) {
        this.login = requireNonBlank(login, "login");
    }

    public void updatePassword(String password) {
        this.password = requireNonBlank(password, "password");
    }

}
