package br.com.fiap.techchallenge.G13.TechChallenge2.G13.core.domain.model;
import br.com.fiap.techchallenge.G13.TechChallenge2.G13.core.domain.enums.UserType;

public class User {

    private String id;
    private String name;
    private UserType type;
    private String email;
    private String login;
    private String password;

    // Note: 'id' is intentionally not included in this constructor.
    // It will be generated by the persistence layer (MongoDB)
    // and can be added later if needed.
    public User(String name, UserType type, String email, String login, String password) {
        this.name = name;
        this.type = type;
        this.email = email;
        this.login = login;
        this.password = password;
    }
}
